#%RAML 1.0 DataType

type: object
properties:
  materialNumber: string | integer
  description: string
  supplier: string
  location: string
  
example:
  materialNumber: "76483398"
  description: "Schäkel"
  supplier: "7000521939 / 10"
  location: "A44E-06211"