#%RAML 1.0 DataType

type: object
properties:
  locationId: string | integer
  shapeLeft: integer
  shapeTop: integer
  shapeHeight: integer
  shapeWidth: integer

example:
  locationId: "A44E06211"
  shapeLeft: 230
  shapeTop: 455
  shapeHeight: 20
  shapeWidth: 20